spring.application.name=simulator

# snake_case global para todos los endpoints
spring.jackson.property-naming-strategy=SNAKE_CASE

# UTF-8 forzado — fix del "â" en lugar de "→"
# UTF-8 — Spring Boot 3.x
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.force-response=true

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/simulator
spring.datasource.username=shtven
spring.datasource.password=gdemg12344

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

mqtt.broker.url=tcp://192.168.1.130:1883
mqtt.client.id=sei-iot-backend
mqtt.topic.subscribe=sei/cuartos/+/#
mqtt.username=admin
mqtt.password=luis5219

audit.queue.capacity=10000000

alarma.setpoint=20.0
alarma.umbral.preventiva=3.0
alarma.umbral.critica=4.0

jwt.secret=BaeJonHyunKangSeulgiSonSeungwanParkSooYoungKimYerim
jwt.expiration-hours=8

control.sistema.operador-id=1
control.cortina.desactivar.delay-seg=5
control.refrigeracion.retorno.delay-seg=30
control.refrigeracion.potencia.alta=100
control.refrigeracion.potencia.base=60

logging.level.com.codespace.simulator=DEBUG
logging.level.org.eclipse.paho=INFO