spring.application.name=simulator

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/simulator
spring.datasource.username=shtven
spring.datasource.password=gdemg12344

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

mqtt.client.id=sei-iot-backend
mqtt.topic.subscribe=sei/cuartos/+/#
mqtt.broker.url=tcp://localhost:1883
mqtt.username=admin
mqtt.password=luis5219

audit.queue.capacity=10000

logging.level.com.codespace.simulator=DEBUG
logging.level.org.eclipse.paho=INFO

INFO  MqttListenerThread - MqttListenerThread suscrito a: sei/cuartos/+/#
