spring.application.name=simulator

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/simulator
spring.datasource.username=shtven
spring.datasource.password=gdemg12344

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

mqtt.broker.url=tcp://${MQTT_BROKER_HOST:172.20.10.9}:${MQTT_BROKER_PORT:1883}
mqtt.client.id=sei-iot-backend
mqtt.topic.subscribe=sei/cuartos/+/#
mqtt.username=admin
mqtt.password=luis5219

audit.queue.capacity=10000

alarma.setpoint=20.0
alarma.umbral.preventiva=3.0
alarma.umbral.critica=4.0

control.sistema.operador-id=1
control.cortina.desactivar.delay-seg=5
control.refrigeracion.retorno.delay-seg=30
control.refrigeracion.potencia.alta=100
control.refrigeracion.potencia.base=60

logging.level.com.codespace.simulator=DEBUG
logging.level.org.eclipse.paho=INFO